// images
import blogImg1 from "../images/blog/blogs-01.jpg";
import blogImg2 from "../images/blog/blogs-02.jpg";
import blogImg3 from "../images/blog/blogs-03.jpg";
import blogImg4 from "../images/blog/da-img04.jpg";
import blogImg5 from "../images/blog/da-img05.jpg";
import blogImg6 from "../images/blog/da-img06.jpg";
import blogImg7 from "../images/blog/img01.jpg";
import blogImg8 from "../images/blog/img02.jpg";
import blogImg9 from "../images/blog/img03.jpg";
import blogImg10 from "../images/blog/cd-img01.jpg";
import blogImg11 from "../images/blog/cd-img02.jpg";
import blogImg12 from "../images/blog/cd-img03.jpg";
import blogImg13 from "../images/blog/img04.jpg";
import blogImg14 from "../images/blog/img05.jpg";
import blogImg15 from "../images/blog/img06.jpg";
import blogImg16 from "../images/blog/img07.jpg";
import banner1 from "../images/blog/blog detail banner-1.png";
import banner2 from "../images/blog/blog detail banner-2.png";
import banner3 from "../images/blog/blog detail banner-3.png";

// import { sub } from "framer-motion";
// import { sub } from "framer-motion/client";



const blogs = [
    {
        id: '1',
        title: 'The Role of BIM in Smarter Construction Projects',
        slug:'The-Role-of-BIM-in-Smarter-Construction-Projects',
        banner: banner1,
        screens: blogImg1,
        description: 'The construction industry is undergoing rapid change, and Building Information Modeling (BIM) has become the cornerstone of smarter, faster, and more efficient projects. At GK Engineering, we use BIM solutions (LOD 100–500) to transform traditional workflows into intelligent, data-driven processes.',
        subtitle1:'What is BIM and Why It Matters',
        subtext1:'BIM is a digital representation of a building’s physical and functional characteristics. Unlike traditional 2D drawings, BIM integrates geometry, data, time, and cost into a single model. This ensures better coordination, reduced errors, and improved decision-making at every stage.',
        subtitle2:'4D & 5D BIM for Smarter Planning',
        subtext2:'BIM allows integration of 4D (time) and 5D (cost) into planning. Using Synchro, we create models that map construction schedules and budgets in real-time. This helps project owners avoid bottlenecks, reduce delays, and maintain control over costs.',
        subtitle3:'Improved Collaboration and Risk Reduction',
        subtext3:'One of BIM’s strongest advantages is collaborative clarity. By acting as a shared model, it unites architects, engineers, contractors, and owners on one platform. This eliminates miscommunication, highlights clashes early, and prevents costly on-site rework.',
        subtitle4:'Facility Management and Long-Term Value',
        subtext4:'BIM isn’t just for construction—it also powers smarter facility management. At GK Engineering, our COBie-compliant data models provide detailed asset information, helping owners streamline maintenance and plan future upgrades.',
        point1:'Visualizing Project Data.',
        point2:'Reducing Construction Errors.',
        point3:'Integrating 4D & 5D.',
        point4:'Enhancing Team Collaboration.',
        point5:'Improving Facility Management.',  
        conclusion:'Conclusion',
        conclusionText:'BIM empowers businesses to reduce risks, lower costs, and improve timelines. With GK Engineering’s BIM solutions, every project gains precision, performance, and long-term value—helping you build smarter from day one.',
        author: 'farugia',
        authorTitle:'Sineor Consultant',
        create_at: 'October 4, 2022',
        comment:'35',
        thumb:'Technology',
        blClass:'format-standard-image',
    },
    {
        id: '2',
        title: 'Why Third-Party MEP Design Review Saves Time and Cost',
        slug:'Why-Third-Party-MEP-Design-Review-Saves-Time-and-Cost',
        banner: banner2,
        screens: blogImg2,
        description: 'Before construction begins, ensuring that MEP designs are accurate, compliant, and efficient is crucial. At GK Engineering, our Third-Party Design Review Services provide independent oversight to help clients reduce risks, optimize costs, and deliver reliable outcomes.',
        subtitle1:'The Importance of Third-Party Design Review',
        subtext1:'Even the best designs can contain hidden flaws. Independent design reviews provide a fresh perspective, identifying errors or gaps that internal teams may overlook. This prevents costly changes during construction and ensures smoother execution.',
        subtitle2:'Ensuring Compliance and Quality',
        subtext2:'Our design review process includes rigorous checks against local and international codes, industry standards, and safety requirements. By validating compliance early, we eliminate risks that could delay approvals or increase costs later.',
        subtitle3:'Identifying Value Engineering Opportunities',
        subtext3:'Beyond compliance, our reviews also highlight opportunities for value engineering—alternative design solutions that reduce costs, streamline layouts, or improve efficiency without compromising safety or performance.',
        subtitle4:'Reducing Risks and Delays',
        subtext4:'Design errors, coordination gaps, and constructability issues can lead to project delays. Through detailed risk assessments, we identify potential pitfalls early, saving both time and money.',
        point1:'Ensuring Design Compliance.',
        point2:'Identifying Hidden Risks.',
        point3:'Optimizing System Performance.',
        point4:'Minimizing Construction Rework.',
        point5:'Boosting Stakeholder Confidence.',  
        conclusion:'Conclusion',
        conclusionText:'A Third-Party MEP Design Review is not just an audit—it’s a safeguard for your investment. With GK Engineering’s expertise, projects benefit from reduced risks, optimized designs, and cost savings before breaking ground.',
        author: 'Andrew',
        authorTitle:'Creative Director',
        create_at: 'October 4, 2023',
        comment:'80',
        thumb:'Branding',
        blClass:'format-standard-image',
    },
    {
        id: '3',
        title: 'How Engineering and BIM Solutions Improve Project Efficiency',
        slug: 'How-Engineering-and-BIM-Solutions-Improve-Project-Efficiency',
        banner: banner3,
        screens: blogImg3,
        description: 'Project efficiency is the backbone of construction success. At GK Engineering, we combine Engineering expertise with BIM solutions to streamline processes, optimize resources, and deliver smarter outcomes.',
         subtitle1:'Engineering Solutions that Build Smarter',
        subtext1:'Our MEP engineering services focus on designing systems that are safe, sustainable, and cost-efficient. From HVAC to electrical and fire protection, every design is optimized for functionality and long-term performance.',
        subtitle2:'BIM as a Game-Changer',
        subtext2:'BIM brings intelligence to project workflows. By integrating design, scheduling, and cost in one model, BIM eliminates guesswork, reduces duplication, and ensures every stakeholder works with accurate information.',
        subtitle3:'Improved Coordination Across Teams',
        subtext3:'Construction projects involve multiple stakeholders. BIM acts as a central hub, allowing engineers, architects, and contractors to collaborate seamlessly. This prevents design clashes, reduces miscommunication, and speeds up execution.',
        subtitle4:'Reducing Rework and Cost Overruns',
        subtext4:'One of the biggest challenges in construction is rework due to design errors. By detecting clashes early in the BIM environment, GK Engineering helps clients avoid costly on-site corrections and stay within budget.',
        point1:'Streamlining Project Workflows',
        point2:'Enhancing Resource Management.',
        point3:'Reducing Operational Costs.',
        point4:'Maximizing Construction Efficiency.',
        point5:'Driving Sustainable Solutions.',  
        conclusion:'Conclusion',
        conclusionText:'Engineering and BIM together drive smarter, faster, and more reliable projects. At GK Engineering, we combine technical precision with digital innovation to ensure every project achieves maximum efficiency and long-term value.',
        author: 'Kurtz',
        authorTitle:'Art Director',
        create_at: 'October 4, 2024',
        comment:'95',
        thumb:'SEO',
        blClass:'format-video',
    },
    {
        id: '4',
        title: 'BIM Solutions Explained: From LOD 100 to LOD 500',
        slug: 'BIM-Solutions-Explained-From-LOD-100-to-LOD-500',
        screens: blogImg4,
        description: 'Digital transformation with IT solutions is about using.',
        author: 'Alex',
        authorTitle:'Art Director',
        create_at: 'October 5, 2023',
        comment:'95',
        thumb:'Branding',
    },
    {
        id: '5',
        title: 'Reducing Construction Risks Through Smarter Engineering',
        slug: 'Reducing-Construction-Risks-Through-Smarter-Engineering',
        screens: blogImg5,
        description: 'The future of cybersecurity relies on innovative IT.',
        author: 'Aliza',
        authorTitle:'Art Director',
        create_at: 'October 6, 2022',
        comment:'95',
        thumb:'Consulting',
    },
    {
        id: '6',
        title: 'Sustainable Building Design: MEP and BIM’s Role in Energy Efficiency',
        slug: 'Sustainable-Building-Design-MEP-and-BIM’s-Role-in-Energy-Efficiency',
        screens: blogImg6,
        description: 'Digital transformation with IT solutions is about..',
        author: 'Tika',
        authorTitle:'Art Director',
        create_at: 'October 9, 2024',
        comment:'95',
        thumb:'Embarking',
    },
    {
        id: '7',
        title: 'How to Prevent Ransomware Attacks, Tips for Businesses..',
        slug: 'How-to-Prevent-Ransomware-Attacks-Tips-for-Businesses..',
        screens: blogImg7,
        description: 'Student visa consulting agencies are equipped with professionals who specialize in the intricacies of visa applications.',
        author: 'Johnson',
        authorTitle:'Art Director',
        create_at: '11/12/2024',
        comment:'95',
        thumb:'Consulting',
    },
    {
        id: '8',
        title: 'Top Cybersecurity Threats Facing Businesses in the year..',
        slug: 'Top-Cybersecurity-Threats-Facing-Businesses-in-the year..',
        screens: blogImg8,
        description: 'The realm of visa applications is a and ever-changing landscape...',
        author: 'Anderson',
        authorTitle:'Art Director',
        create_at: '18/12/2024',
        comment:'95',
        thumb:'Consulting',
    },
    {
        id: '9',
        title: 'Common cyber threats and how to prevent them..',
        slug: 'Common-cyber-threats-and-how-to-prevent-them..',
        screens: blogImg9,
        description: 'Embarking on a journey to study abroad is an aspiration many students..',
        author: 'Martinez',
        authorTitle:'Art Director',
        create_at: '27/12/2024',
        comment:'95',
        thumb:'Consulting',
    },
    {
        id: '10',
        title: 'DevOps for Both Discontinuous and Continuous Improvements',
        slug: 'DevOps-for-Both-Discontinuous-and-Continuous-Improvements',
        screens: blogImg10,
        description: 'Student visa consulting agencies are equipped with professionals who specialize in the intricacies of visa applications.',
        author: 'Alex Olebar',
        authorTitle:'Art Director',
        create_at: '11/12/2024',
        comment:'95',
        thumb:'Consulting',
    },
    {
        id: '11',
        title: 'Five Great DevOps Job Opportunities',
        slug: 'Five-Great-DevOps-Job-Opportunities',
        screens: blogImg11,
        description: 'The realm of visa applications is a and ever-changing landscape...',
        author: 'Rakim Yakun',
        authorTitle:'Art Director',
        create_at: '18/12/2024',
        comment:'95',
        thumb:'Consulting',
    },
    {
        id: '12',
        title: 'Anthropic AI Model Automates Developer Mouse Movements',
        slug: 'Anthropic-AI-Model-Automates-Developer-Mouse-Movements',
        screens: blogImg12,
        description: 'Embarking on a journey to study abroad is an aspiration many students..',
        author: 'Kim Jung',
        authorTitle:'Art Director',
        create_at: '27/12/2024',
        comment:'95',
        thumb:'Consulting',
    },
    {
        id: '13',
        title: 'Innomax Launches AI-Support..',
        slug: 'Innomax-Launches-AI-Support',
        screens: blogImg13,
        read:'3 min read',
    },
    {
        id: '14',
        title: 'New Features Boost Innomax Support Solutions..',
        slug: 'New-Features-Boost-Innomax-Support-Solutions',
        screens: blogImg14,
        read:'4 min read',
    },
    {
        id: '15',
        title: 'Innomax Enhances Support with AI Automation..',
        slug: 'Innomax-Enhances-Support-with-AI-Automation..',
        screens: blogImg15,
        read:'8 min read',
    },
    {
        id: '16',
        title: 'Innomax AI Deflects 15% of Support Tickets..',
        slug: 'Innomax-AI-Deflects-15%-of-Support-Tickets..',
        screens: blogImg16,
        read:'9 min read',
    }
];
export default blogs;